{
  backend: { name: git-gateway },

  media_folder: static/cms,
  public_folder: /cms,

  locale: fr,

  collections: [
      {
        name: blog,
        label: Blog,
        # format: "json"
        folder: '/content/blog',
        create: true,
        slug: '{{year}}-{{month}}-{{day}}-{{slug}}',
        # editor:
        #   preview: false
        fields: [
            { label: 'Title', name: 'title', widget: 'string' },
            { label: 'Date', name: 'date', widget: 'date' },
            # { label: 'Description', name: 'description', widget: 'string' },
            { label: 'Corps', name: 'body', widget: 'markdown' },
          ],
      },
    ],
}
